# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FireBaseStudy1' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FireBaseStudy1
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'

end
